image: microsoft/aspnetcore-build:2.0
# 加入服務
services:
#  - redis
  - mongo

# 設定工作階段
stages:
  - build
  - test

# 執行前檢查
before_script:
  # 版本
  #- dotnet --version
  #- ping redis -c 5
  #- ping mongo -c 5

# 工作job
build_job:
  stage: build
  only:
    - master
  script:
    - dotnet restore ./app/APISample.csproj --verbosity m
    - dotnet publish ./app/APISample.csproj

# 工作test
test_job:
  stage: test
  only:
    - master
  script:
    - sudo apt-get install redis-server
    - dotnet restore ./test/MyFirstUnitTests.csproj --verbosity m
    - dotnet build ./test/MyFirstUnitTests.csproj 
    - cp ./app/appsettings_gitlab.json ./test/bin/Debug/netcoreapp2.0/appsettings.json    
    - cd test
    - dotnet test
