image: microsoft/aspnetcore-build:2.0


# 設定工作階段
stages:
  - build
  - test
  - deploy

# 執行前檢查
before_script:
  # 版本
  #- dotnet --version
  # - ping redis -c 1
  #- ping mongo -c 5

# 工作job
build_job:
  stage: build
  only:
    - master
  script:
    - dotnet restore ./app/APISample.csproj --verbosity m
    - dotnet publish ./app/APISample.csproj
  
# 工作test
test_job:
  stage: test
  only:
    - master
  # 加入服務
  services:
    - redis
    - mongo
  script:    
    - dotnet restore ./test/MyFirstUnitTests.csproj --verbosity m
    - dotnet build ./test/MyFirstUnitTests.csproj 
    - cp ./app/appsettings_gitlab.json ./test/bin/Debug/netcoreapp2.0/appsettings.json    
    - cd test
    - dotnet test

# 工作test
deploy_job:
  stage: deploy
  script:
    - echo Deploy OK
    - cd app
    - docker build -t apisample-image .
    - docker save -o apisample.tar apisample-image
  #會把裡面編譯或程式的產出物存放起來，提供介面給其他需要的人使用
  artifacts:
    paths:
      - ./app/apisample.tar



 
