language: csharp
mono: none
dotnet: 2.1.3
services:
  - mongodb
  - redis-server
script:
 - dotnet --version
 - dotnet restore ./app/APISample.csproj --verbosity m
 - dotnet publish ./app/APISample.csproj
 - dotnet restore ./test/MyFirstUnitTests.csproj --verbosity m
 - dotnet build ./test/MyFirstUnitTests.csproj --verbosity m
 - cd test
 - dotnet test