version: '1.0.{build}'
image: Visual Studio 2017
services:
  - mongodb
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./app/APISample.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./app/APISample.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\bin\Debug\netcoreapp2.0\publish'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./test/MyFirstUnitTests.csproj --verbosity m
  - cmd: tree ./test
  # 複製appsettings.json
  - cmd: cp ./app/appsettings_appveyor.json ./test/bin/Debug/netcoreapp2.0/appsettings.json
  # run the unit tests (requires changing into the test directory)
  - cmd: cd test
  - cmd: dotnet test
on_finish :
  # any cleanup in here
deploy: off